language: go
go:
  - 1.13.x

go_import_path: github.com/spikerlabs/godog

install: go install github.com/spikerlabs/godog/cmd/godog

script:
  - go vet github.com/spikerlabs/godog
  - go vet github.com/spikerlabs/godog/gherkin
  - go vet github.com/spikerlabs/godog/colors
  - test -z "$(go fmt ./...)" # fail if not formatted properly
  - godog -f progress
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
